### ISSUE TITLE
Adding Deadline and Task Cannot Work 

### ISSUE THREAD

**Issue by t170815518** [johan9se/ip#5]
Based on the example given in UG, `deadline` command seems not working properly.
```
deadline iP final submission /by 2020-10-02 23:59
	_________________________________
	 Please provide a date/time for this deadline description!
	_________________________________
```
So is the event command 
```event CS2113T exam /at 2020-12-01 13:00 /to 2020-12-01 14:00
	_________________________________
	 Please provide a date/time for this event description!
	_________________________________
```

**Comment by johan9se** [comment]
I believe this was a mistake on my part. My code required the use of '/by' and '/at' for adding Deadlines and Events (notice the use of backslashes instead of forward slashes).  Unfortunately, my User Guide did not reflect the correct command, but the message displayed using my 'help' command did. Thank you for bringing this up, it has been resolved.
